/* Modelagem Básica -
ENTIDADE = TABELA
CAMPOS = ATRIBUTOS*/

CLIENTE

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER (1)

/* PROCESSSOS DE MODELAGEM */

/* FASE 01 E FASE 02 - ADM DE DADOS */

MODELAGEM CONCEITUAL - RASCUNHO MENTAL
MODELAGEM LÓGICA - PROGRAMAS DE MODELAGEM

/* FASE 03 - ADM DE DB ou ADM DE DADOS */

MODELAGEM FÍSICA - SCRIPS DE BANCO

/* INICIANDO MODELAGEM FÍSICA */

/* CRIANDO BANCO DE DADOS */

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO */

USE PROJETO;

/* CRIANDO TABELA DE CLIENTES */

CREATE TABLE CLIENTE (

	NOME VARCHAR(30),
	CPF INT (11),
	EMAIL VARCHAR(30),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100),
	SEXO CHAR(1)
	
);

/* VERIFICANDO TABELAS DO BANCO */

SHOW TABLES;

USE EXEMPLO;
SHOW TABLES;

USE PROJETO;

/* DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA */

DESCRIBE CLIENTE;
Ou
DESC CLIENTE;

/* FORMA 01 - sintaxe básica de inserção -INSERT INTO TABELA... */

INSERT INTO CLIENTE VALUES(valor1, valor2, valor3, valor4, valor5, valor6)

/* FORMA 02 - COLOCANDO COLUNAS, ESPECIFICANDO ORDEM QUE DESEJAR */


INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES(valor1, valor2, valor3, valor4, valor5)

/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */

INSERT INTO CLIENTE VALUES(valor1,valor2,valor3,valor4,valor5,valor6),
							(valor1,valor2,valor3,valor4,valor5,valor6);

/* O COMANDO SELECT - SELECAO PROJECAO E JUNCAO */

SELECT NOW();	/* DATA E HORA */

SELECT 'ALGUMA COISA' /* RETORNA 'ALGUMA COISA' */

SELECT NOME AS CLIENTE, SEXO, EMAIL, ENDERECO FROM CLIENTE; /* ESTA PROJETANDO UMA COLUNA, SUBSTITUINDO 'NOME' POR 'CLIENTE' */

SELECT CPF, NOME, EMAIL, SEXO FROM CLIENTE

/* SELECAO GERAL */

SELECT * FROM CLIENTE;

/* NAO UTILIZAR DE FORMA PROFISSIONAL
IGNORA INDICES E TRAZ TODO O CONTEUDO DA TABELA OU BANCO
SOLUÇÃO: MOSTRAR APENAS O NECESSARIO PARA AJUDAR NO PROCESSAMENTO
MOMENTOS VALIDOS PARA USAR *: ESTUDOS ACADEMICOS COM POUCOS DADOS OU SIMILARES
*/

/* SELECAO COM FILTROS */

SELECT NOME,SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'F';

/* OPERADOR LIKE
UTILIZA CARACTER CORINGA
% SIGNIFICA QUALQUER SEQUENCIA DE CARACTERES
OU SEJA
SELECT ... WHERE NOME LIKE 'A%'; RETORNA AS ROWS EM QUE NOME TEM O CARACTER A INDEPENDENTEMENTE DO QUE VEM DEPOIS
SELECT ... WHERE NOME LIKE '%ABC%'; RETORNA AS ROWS EM QUE NOME TEM A SEQUENCIA 'ABC', INDEPENDENTEMENTE DO QUE VEM ANTES OU DEPOIS
*/

SELECT NOME, SEXO, TELEFONE FROM CLIENTE
WHERE NOME LIKE 'A %';

/* COUNT(*), GROUP BY, PERFORMANCE COM OPERADORES LOGICOS */

/* CONTANTO OS REGISTROS DE UMA TABELA */

SELECT COUNT(*) AS 'Quantidade de Registros da Tab.Cliente' FROM CLIENTE;

/* GROUP BY - AGRUPAMENTO */

SELECT SEXO, COUNT(*)
FROM CLIENTE
GROUP BY SEXO;

/* PERFORMANCE

NO OR COLOCAR O VALOR QUE TEM MAIS PROBABILIDADE PRIMEIRO,
ASSIM AUMENTA AS CHANCES DA QUERY SER RESPONDIDA COM APENAS UM VALOR,
JÁ QUE NO OPERADOR OR SE ALGUM DOS DOIS FOR VERDADEIRO ELE JÁ RETORNA VERDADEIRO

NO AND COLOCAR QUEM TEM MENOS PROBABILIDADE PRIMEIRO,
ASSIM AUMENTA AS CHANCES DO BANCO JÁ DESQUALIFICAR A ROW PARA A QUERY USANDO APENAS UM VALOR,
JÁ QUE COM O OPERADOR AND SE ALGUM DOS DOIS FOR FALSO ELE JÁ RETORNA FALSO

*/
